#%RAML 1.0 DataType
type: object
displayName: create-patient-request
properties:
  title:
    type: string
    required: false
  firtsName: 
    type: string
    required: false
  lastName: 
    type: string
    required: false
  gender: 
    type: string
    required: false
  age: 
    type: number
    required: false
  email: 
    type: string
    required: false
  phoneNumber: 
    type: number
    required: false